# -*- coding: utf-8 -*-
"""CASchools

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y5eqkEY3sMk4oLP_i6exDY0mCaIIkd-Q
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
from google.colab import drive
#drive.mount("/content/drive")
df = pd.read_csv("/content/drive/MyDrive/CASchools.csv")



# Basic Data Analysis
def analyze_data(df):
    print("Data Summary:")
    print(df.describe())
    print("\nMissing Values:")
    print(df.isnull().sum())

# Visualize Data
def plot_data(df):
    plt.figure(figsize=(14, 8))

    # Plot average reading scores
    plt.subplot(2, 2, 1)
    sns.histplot(df['read'], bins=20, kde=True)
    plt.title('Average Reading Scores')

    # Plot average math scores
    plt.subplot(2, 2, 2)
    sns.histplot(df['math'], bins=20, kde=True)
    plt.title('Average Math Scores')

    # Plot student enrollment distribution
    plt.subplot(2, 2, 3)
    sns.histplot(df['students'], bins=20, kde=True)
    plt.title('Student Enrollment Distribution')

    # Plot expenditure per student
    plt.subplot(2, 2, 4)
    sns.histplot(df['expenditure'], bins=20, kde=True)
    plt.title('Expenditure per Student')

    plt.tight_layout()
    plt.show()

# Main function
def main():
    # Analyze the data
    analyze_data(df)

    # Plot the data
    plot_data(df)

if __name__ == "__main__":
    main()

# Analyze Income vs. Scores
def analyze_income_vs_scores(df):
    plt.figure(figsize=(12, 6))

    # Scatter plot for Income vs. Reading Scores
    plt.subplot(1, 2, 1)
    sns.scatterplot(data=df, x='income', y='read')
    plt.title('Income vs. Reading Scores')
    plt.xlabel('Income (in $1,000)')
    plt.ylabel('Reading Score')

    # Scatter plot for Income vs. Math Scores
    plt.subplot(1, 2, 2)
    sns.scatterplot(data=df, x='income', y='math')
    plt.title('Income vs. Math Scores')
    plt.xlabel('Income (in $1,000)')
    plt.ylabel('Math Score')

    plt.tight_layout()
    plt.show()

    # Calculate and print correlation coefficients
    corr_read = df['income'].corr(df['read'])
    corr_math = df['income'].corr(df['math'])
    print(f"Correlation between Income and Reading Scores: {corr_read:.2f}")
    print(f"Correlation between Income and Math Scores: {corr_math:.2f}")

# Main function
def main():
    # Analyze the data
    analyze_data(df)

    # Plot the data
    plot_data(df)

    # Analyze income vs. scores
    analyze_income_vs_scores(df)

if __name__ == "__main__":
    main()