# -*- coding: utf-8 -*-
"""Vocab and Education

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17wAETrXEAwnmMjt1vscP5SD4qZcwzEmY
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
from google.colab import drive
drive.mount("/content/drive")
df = pd.read_csv("/content/drive/MyDrive/Vocab.csv")

# Basic Data Analysis
def analyze_data(df):
    print("Data Summary:")
    print(df.describe())
    print("\nMissing Values:")
    print(df.isnull().sum())

# Visualize Data
def plot_data(df):
    plt.figure(figsize=(14, 8))

    # Plot histogram of education
    plt.subplot(2, 2, 1)
    sns.histplot(df['education'], bins=20, kde=True)
    plt.title('Distribution of Education')

    # Plot histogram of vocabulary scores
    plt.subplot(2, 2, 2)
    sns.histplot(df['vocabulary'], bins=10, kde=True)
    plt.title('Distribution of Vocabulary Scores')

    # Plot count plot of sex
    plt.subplot(2, 2, 3)
    sns.countplot(data=df, x='sex')
    plt.title('Count of Respondents by Sex')

    plt.tight_layout()
    plt.show()

# Analyze Relationships
def analyze_relationship(df):
    plt.figure(figsize=(10, 6))

    # Scatter plot for Education vs. Vocabulary Score
    sns.scatterplot(data=df, x='education', y='vocabulary', hue='sex', alpha=0.5)
    plt.title('Education vs. Vocabulary Score')
    plt.xlabel('Years of Education')
    plt.ylabel('Vocabulary Score')

    plt.tight_layout()
    plt.show()

    # Calculate and print correlation coefficient
    corr = df['education'].corr(df['vocabulary'])
    print(f"Correlation between Education and Vocabulary Score: {corr:.2f}")

# Analyze Education Trends Over Time
def analyze_education_trends(df):
    # Calculate average education per year
    education_trends = df.groupby('year')['education'].mean().reset_index()

    plt.figure(figsize=(10, 6))
    sns.lineplot(data=education_trends, x='year', y='education', marker='o')
    plt.title('Average Years of Education Over Time')
    plt.xlabel('Year')
    plt.ylabel('Average Years of Education')
    plt.grid(True)
    plt.tight_layout()
    plt.show()

    print("Average Education per Year:")
    print(education_trends)

# Main function
def main():
    # Analyze the data
    analyze_data(df)

    # Plot the data
    plot_data(df)

    # Analyze relationships
    analyze_relationship(df)

    # Analyze education trends over time
    analyze_education_trends(df)

if __name__ == "__main__":
    main()